### ISSUE TITLE
geopandas package

### ISSUE THREAD

**Issue by Morenagl** [Morenagl/geopandas#1]
hello, I have a problem with importing geopandas package, I have created my new environment in Conda and I the installation has done but in jupyter book doesn t work 
![geopandas](https://user-images.githubusercontent.com/53742915/62772552-22081700-baa0-11e9-9cd4-5188e74efd48.PNG)

and the error Command "python setup. py egg_info" failed with error code 1 in C so I have noticed that it's not in the same path I mean the same environment which is normal that it could not do it, so how can I change the environment in jupyter book just to import geopandas and the same time not lose all my packages in Conda because I have found already trouble with pysal package and I don't want they have the same issue 
 thank you @darribas @sjsrey @ljwolf

**Comment by darribas** [comment]
Hello, I'd recommend you ask this question on the Gitter channel for geopandas, which is very active and helpful:

https://gitter.im/geopandas/geopandas

I'd also suggest to install the package through a package manager such as pip or, ideally, conda as that will deal with dependencies, etc.

**Comment by Morenagl** [comment]
@darribas thank you for responding the problem i updatated conda many time and he cant deal withe the other dependencies that why the environment could not do it i ll post it on the link thank you
